---
"apiVersion": "Service"
"kind": "v1"
"metadata": 
  "name": "minecraft-service"
"spec": 
  "ports": 
  - "name": "minecraft-server"
    "port": 8080
    "targetPort": 8080
  - "name": "minecraft-client"
    "port": 25675
    "targetPort": 25675
  "selector": 
    "app": "minecraft"
    "env": "test"
  "type": "ClusterIP"
---
"apiVersion": "apps/v1"
"kind": "Deployment"
"metadata": 
  "labels": 
    "app": "minecraft"
  "name": "test"
"spec": 
  "selector": 
    "matchLabels": 
      "app": "minecraft"
      "env": "test"
  "template": 
    "metadata": 
      "labels": 
        "app": "minecraft"
        "env": "test"
    "spec": 
      "containers": 
      - "command": "echo hello minecraft!"
        "env": 
        - "name": "app"
          "value": "minecraft"
        - "name": "app"
          "valueFrom": 
            "configMapKeyRef": 
              "key": "name"
        - "name": "app"
          "valueFrom": 
            "fieldRef": 
              "fieldPath": "test"
        - "name": "app"
          "valueFrom": 
            "resourceFieldRef": 
              "resource": "test"
        "image": "mpolatcan/minecraft"
        "imagePullPolicy": "IfNotPresent"
        "lifecycle": 
          "postStart": 
            "exec": 
              "command": "echo"
          "preStop": 
            "tcpSocket": 
              "host": "localhost"
              "port": 8080
        "name": "minecraft"
        "ports": 
        - "containerPort": 8080
          "name": "minecraft-server"
          "protocol": "TCP"
        - "containerPort": 25675
          "name": "minecraft-client"
          "protocol": "TCP"
        "readinessProbe": 
          "exec": 
            "command": "echo hello world"
          "initialDelaySeconds": 3
        "resources": 
          "limits": 
            "cpu": "500Mi"
            "memory": "1Gi"
          "requests": 
            "cpu": "200Mi"
            "memory": "512Mi"
        "securityContext": 
          "runAsGroup": 1000
          "runAsUser": 1000
        "stdin": true
        "stdinOnce": true
        "tty": true
        "volumeMounts": 
        - "mountPath": "/"
          "name": "minecraft-vol"
          "readOnly": false
      "initContainers": 
      - "command": "git pull"
        "image": "mpolatcan/echo"
        "imagePullPolicy": "IfNotPresent"
        "name": "minecraft"
...

